apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: appcloud
  labels:
    app: ui
spec:
  selector:
    app: ui
  ports:
    - name: http
      port: 4000
      targetPort: 4000
  type: ClusterIP
